name: Python Code Checks

on: [push, pull_request]

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Flake8
      run: |
        flake8 --exclude=__init__.py

    - name: Check for Changes
      run: git diff --exit-code

    - name: Set Exit Code
      id: check-exit-code
      run: echo ::set-output name=exit_code::${{ steps.RunTests.outcome }}

    - name: Fail Workflow on Errors
      if: ${{ steps.check-exit-code.outputs.exit_code != 'success' }}
      run: exit 1
